set(MODULES
	src/Windowing/Exceptions/SdlException.cppm
	src/Windowing/Exceptions/SdlInitializationException.cppm
	src/Windowing/Exceptions/SdlRendererException.cppm
	src/Windowing/Exceptions/SdlWindowException.cppm
	src/Windowing/Exceptions.cppm
	src/Windowing/WindowBuilder.cppm
	src/Windowing/WindowSize.cppm
	src/Windowing/WindowState.cppm
	src/AppInfo.cppm
	src/Game.cppm
)
